Added reranker.py
effectz-ai/effectz-gpt pull request #9
Opened 2024-08-17 10:35 UTC by iujinasena

Please review.

2024-08-19 10:33 UTC, deltaaruna requested changes
Nice job.
Please look at my comment and implement it.

2024-08-19 10:33 UTC, deltaaruna commented on effectzgpt/backend/app/engine/__init__.py
Pls add these things
1) In app.engine.node_postprocessors, define a method to return the reranker(We have only cohere reranknig implemented, so check if the cohere api key is available, if so, return the cohere reranker from reranker.py)
2) Check of the reranking is enabled. If enabled, get the reranker. Something like the following.
if os.getenv("IS_RERANKER_ENABLED", "True").lower() == "true":
        node_postprocessors.append(get_reranker())

Pls refer to sentence window retrieval implementation for more info.

2024-08-21 03:31 UTC, iujinasena commented on effectzgpt/backend/app/engine/__init__.py
Requested changes have been implemented. Please review, @deltaaruna .

2024-08-22 14:05 UTC, nilaan-effectz requested changes

2024-08-22 14:05 UTC, nilaan-effectz commented on effectzgpt/backend/app/engine/constants.py
> +DEFAULT_TOP_K = 3
use DEFAULT_COHERE_TOP_K  and refactor usages

2024-08-22 14:05 UTC, nilaan-effectz commented on effectzgpt/backend/app/engine/reranker.py
> +    top_k = int(os.getenv("TOP_K", DEFAULT_TOP_K))
TOP_K is already in use , use COHERE_TOP_K 
add these env variable to .env file

2024-08-22 14:05 UTC, nilaan-effectz commented on effectzgpt/backend/app/engine/__init__.py
> +    cohere_rerank = get_cohere_reranker()
remove this line 
in line 42  'node_postprocessors.append(cohere_rerank)'
use if condition 
`
if os.getenv("IS_RERANKER_ENABLED").lower() == "true" :
    cohere_rerank = get_cohere_reranker()
   node_postprocessors.append(cohere_rerank)
`
make sure you added this env varible to .env file (default set it to false )

2024-08-27 03:41 UTC, deltaaruna commented
Looks good. Please resolve the conflicts. Then this can be merged. Thanks @iujinasena

2024-08-28 03:07 UTC, nilaan-effectz approved these changes

2024-08-28 03:08 UTC, merged